version: '3'

services:
  rabbitmq:
      image: "rabbitmq:management"
      ports:
        - "15672:15672"
        - "5672:5672"
  eureka:
    #image: maven:3.6.1-jdk-8
    build: ./eureka-server
    ports:
      - '8761:8761'
    working_dir: /app
    volumes:
      - ./eureka-server:/app
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  api-gateway:
    #image: maven:3.6.1-jdk-8
    build: ./api-gateway
    ports:
      - '8080:8080'
    working_dir: /app
    volumes:
      - ./api-gateway:/app
    depends_on:
      - eureka
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  postgresdev:
    image: postgres
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=postgres
     - POSTGRES_DB=pguser
  postgresdev2:
    image: postgres
    ports:
     - "5433:5432"
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=postgres2
     - POSTGRES_DB=pgpost
  postgresdev3:
    image: postgres
    ports:
     - "5434:5432"
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=postgres3
     - POSTGRES_DB=pgcomment
  user-api:
    #image: maven:3.6.1-jdk-8
    build: ./user-api
    ports:
      - '8081:8081'
    working_dir: /app
    volumes:
      - ./user-api:/app
    depends_on:
      - eureka
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  post-api:
    #image: maven:3.6.1-jdk-8
    build: ./post-api
    ports:
      - '8082:8082'
    working_dir: /app
    volumes:
      - ./post-api:/app
    depends_on:
      - eureka
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    links:
      - rabbitmq
  comment-api:
    #image: maven:3.6.1-jdk-8
    build: ./comment-api
    ports:
      - '8083:8083'
    working_dir: /app
    volumes:
      - ./comment-api:/app
    depends_on:
      - eureka
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    links:
      - rabbitmq
  email-service:
    #image: maven:3.6.1-jdk-8
    build: ./email-service
    ports:
      - '8084:8084'
    working_dir: /app
    volumes:
      - ./email-service:/app
    depends_on:
      - eureka
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    links:
      - rabbitmq

