pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /tmp/.m2:/tmp/.m2 -u root'

        }
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {0
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test -Dspring.profiles.active=test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Coverage') {
            steps {
                sh 'mvn cobertura:cobertura -Dcobertura.report.format=xml'
            }
            post {
              always {
                cobertura coberturaReportFile: 'target/site/cobertura/coverage.xml'
                }
            }
        }
    }
}
